version: '3'
services:
  web1:
    image: nginx:alpine
    depends_on:
      - web2
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/tmp/nginx.conf
      - ./web1:/usr/share/nginx/html/web1
    command: /bin/sh -c "envsubst '$$NGINX_UPSTREAM_SERVER1 $$NGINX_UPSTREAM_SERVER2' < /tmp/nginx.conf > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"
    environment:
      NGINX_PORT: 80
      NGINX_UPSTREAM_SERVER1: "172.26.0.3"
      NGINX_UPSTREAM_SERVER2: "172.26.0.2"
  web2:
    image: nginx:alpine
    depends_on:
      - web3
    ports:
      - "8081:80"
    volumes:
      - ./nginx.conf:/tmp/nginx.conf
      - ./web2:/usr/share/nginx/html/web2
    command: /bin/sh -c "envsubst '$$NGINX_UPSTREAM_SERVER1 $$NGINX_UPSTREAM_SERVER2' < /tmp/nginx.conf > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"
    environment:
      NGINX_PORT: 80
      NGINX_UPSTREAM_SERVER1: "172.26.0.4"
      NGINX_UPSTREAM_SERVER2: "172.26.0.3"
  web3:
    image: nginx:alpine
    ports:
      - "8082:80"
    volumes:
      - ./nginx.conf:/tmp/nginx.conf
      - ./web3:/usr/share/nginx/html/web3
    command: /bin/sh -c "envsubst '$$NGINX_UPSTREAM_SERVER1 $$NGINX_UPSTREAM_SERVER2' < /tmp/nginx.conf > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"
    environment:
      NGINX_PORT: 80
      NGINX_UPSTREAM_SERVER1: "172.26.0.4"
      NGINX_UPSTREAM_SERVER2: "172.26.0.2"
